name: 'Release Drafter'

on:
  pull_request:
   branches:
    - release/*
  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Calculate Tags to Compare
        id: calculate_compare_tags
        run: |
          env
          echo GITHUB_REF $GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/*}
          TARGET_RELEASE=${GITHUB_REF#refs/heads/release/*}
          echo Branch Name $BRANCH
          echo Target Release $TARGET_RELEASE
          echo "::set-output name=BRANCH_NAME::$BRANCH"
          echo "::set-output name=TARGET_RELEASE::$TARGET_RELEASE"
      
#      - name: Build Changelog
#        id: github_release
#       uses: mikepenz/release-changelog-builder-action@v1
#        with:
#          failOnError: true
#          configuration: ".github/release_config.json"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
#      - name: Echo Changelog
#        env:
#          CHANGELOG: ${{ steps.github_release.outputs.changelog }}
#        run: echo "$CHANGELOG"          
